DROP USER PERSONAL_CODE CASCADE
/

CREATE USER PERSONAL_CODE IDENTIFIED BY test_password
/

GRANT CONNECT, RESOURCE TO PERSONAL_CODE
/

GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE SYNONYM TO PERSONAL_CODE
/

GRANT CREATE SESSION TO PERSONAL_CODE
/

GRANT UNLIMITED TABLESPACE TO PERSONAL_CODE
/
